### ISSUE TITLE
Не подходит для больших объемов

### ISSUE THREAD

**Issue by legale** [notdest/yandex-yml-generator#3]
Интересная идея. Однако надо бы оптимизировать. 4 гб для простой формировалки xml - перебор. Почему вообще потребляемая память пропорциональна размеру выходного файла? Формируем товар, очищаем память и формируем следующий. Так должно быть.

**Comment by notdest** [comment]
У магазина, у которого есть 200 000 предложений на маркете, скорее всего гораздо больше памяти. Так в целом, заказ услышан и будет реализован чуть позже, сейчас с временем не очень.

Кстати, этот репозиторий был указан у меня в резюме, и его производительность очень классно обосрали в офисе тикетлэнда)

**Comment by legale** [comment]
Понятно.  :) Давно вообще в программировании?

**Comment by notdest** [comment]
давно но вяленько. 
В 2009 устроился пыхарем, полгода поработал, потом полгода доучивался в технаре, попутно вынося из фирмы то, что мне не доплатили. 
Потом ещё полгода пыхарем,
далее год фуллстек, кроме дизайна,
далее универ, 5-6лет с учетом поступления, академа и отходняка. Внутри него условно полгода на  C под оборонку, чуть не устроился на НИР.
2 недели назад устроился в огроменное издательство пыхарем

**Comment by legale** [comment]
Биография прямо. А я пару лет пыхаю только. Вот потихоньку полегоньку вроде
что-то стало получаться, но все равно со скрипом. Я вообще юрист по
образованию.

**Comment by notdest** [comment]
сорян, мне просто HR этот вопрос уже раз 100 задали, правда они слышали совсем другую версию) Вообще читать "пару лет" и "со скрипом" в одном тексте вызывает какой-то диссонанс, что ты считаешь скрипом?

**Comment by legale** [comment]
Но в 20 веке это было почти нормально. :-) со скрипом значит, что программы из под моей руки все ещё ведут себя непредсказуемо. Большая часть ошибок устраняется уже только на тестировании. Вот это значит со скрипом. On 2018-05-19 21:50 , Alex Solodov Wrote: сорян, мне просто HR этот вопрос уже раз 100 задали, правда они слышали совсем другую версию) Вообще читать "пару лет" и "со скрипом" в одном тексте вызывает какой-то диссонанс, что ты считаешь скрипом? — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by notdest** [comment]
Поправил, потребление памяти 2 Мб независимо от количества товарных предложений.
