### ISSUE TITLE
Fatal error: Cannot use object of type DOMNodeList as array

### ISSUE THREAD

**Issue by ermushko** [notdest/yandex-yml-generator#4]
Нужно поменять вызовы
`$dlv = $dlvs[0];`
на
`$dlv = $dlvs->item(0);`

Относится к delivery и dlvOption

**Comment by notdest** [comment]
Прикольно, у меня и так и так работает, поправил. А на какой версии php и xml он это выдал?

**Comment by ermushko** [comment]
Это OpenServer, локалка, но все же 

> PHP 5.5
> DOM/XML API Version | 20031129
> libxml Version | 2.9.1

Да и я выяснил, что эти паскудники не поддерживают кириллические домены, так что не пригодилось, а жаль ;(

**Comment by notdest** [comment]
ладно, зато у меня скрипт теперь выполняется за 140 сек вместо 143 и запускается на большем разнообразии серверов. Спасибо, что написал.
